name: Oblig3_CI 

on: [push] 

jobs: 
  build:
    name: "Run tests" 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checking out code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'
      - name: Install poetry
      - uses: abatilo/actions-poetry@v2.0.0
        with: 
          poetry-version: '1.1.11'
      - name: Build
        run: |
          poetry install
      - name: Run tests 
        run: |
          poetry run pytest -r w
